version: 2
sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

formats: all

python:
   install:
   - requirements: requirements.txt
